# Generated by Django 3.2.16 on 2023-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=30)),
                ('Pprice', models.IntegerField()),
                ('Pimage', models.ImageField(upload_to='user_directory_path')),
                ('Plink', models.CharField(max_length=350)),
            ],
        ),
    ]
